spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/user
      username: root
      password: 123456
weibo:
  clientId: 2794712645
  clientSecret:
  redirectUri: https://passport.yhd.com/sina/callback.do
mybatis:
  mapper-locations: me.jastz.*.*.mapper
  type-aliases-package: me.jastz.*.*.entity
  configuration:
    map-underscore-to-camel-case: true